# Generated by Django 3.1.7 on 2021-03-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Vegetables',
        ),
    ]
