# Generated by Django 3.1.7 on 2021-04-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_oils_seasonings'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='oils',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinner.recipe')),
            ],
        ),
    ]
