# Generated by Django 3.1.7 on 2021-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsfordinner', '0003_recipe_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_id',
            field=models.IntegerField(null=True),
        ),
    ]
