# Generated by Django 3.1.7 on 2021-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsfordinner', '0005_auto_20210413_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.IntegerField(),
        ),
    ]
