# Generated by Django 3.1.7 on 2021-04-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsfordinner', '0006_auto_20210413_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
    ]
